### ISSUE TITLE
Implement "Friend Activity"

### ISSUE THREAD

**Issue by ItsCentric** [ItsCentric/music-wizard-website#10]
Similar to friend activity on Spotify, implement a section that shows a user's friends/following on Spotify in descending order based on how recent their activity was

### Information

- User profile picture
- User name
- Name of most recent track
- Duration of most recent track
- How long ago the track was played

### Tasks

- [ ] Layout "friend activity" section
- [ ] Layout a "friend activity" item
- [ ] Implement relevant information
